1. Импорт библиотеки NumPy с общепринятым сокращением

In [1]:
# стандартный импорт numpy
import numpy as np

2. Примеры создания массивов

In [2]:
# создания массивов из обычных списков
arr_list1 = np.array([1, 2, 3])
arr_list2 = np.array(list((4, 5, 6)))
# создания массивов с использованием методов numpy
arr_zeros = np.zeros((3, 5)) # матрица нулей
arr_ones = np.ones(3) # матрица единиц
arr_eye = np.eye(4) # единичная матрица 
arr_arange = np.arange(1, 11, 2) # массив от 1 до 11 с шагом 2
arr_empty = np.empty((3, 2)) # массив с "мусорными" значения
arr_list2, arr_eye

(array([4, 5, 6]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

3. Демонстрация атрибутов

In [3]:
# вывод формы массивов
arr_zeros.shape, arr_ones.shape

((3, 5), (3,))

In [4]:
# вывод типа данных массивов
arr_arange.dtype, arr_empty.dtype

(dtype('int32'), dtype('float64'))

4. Примеры индексирования и срезов

In [5]:
# получение отдельного элемента;
arr_list1[0], arr_eye[0,0]

(1, 1.0)

In [6]:
# извлечение подмассива с помощью среза
arr_arange[2:5], arr_eye[2:4,1:4]

(array([5, 7, 9]),
 array([[0., 1., 0.],
        [0., 0., 1.]]))

5. Примеры векторных операций и базовых статистик

In [7]:
# поэлементное сложение или умножение массивов
arr_arange + np.arange(3, 12, 2), 2 * arr_ones * np.eye(3)

(array([ 4,  8, 12, 16, 20]),
 array([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]]))

In [8]:
# вычисление простой статистики
arr_random = np.random.randint(0,5,(2,3))
print(f"""Случайный массив:\n{arr_random}
Среднее: {np.mean(arr_random)}
Медиана: {np.median(arr_random)}
Стандартное отклонение: {np.std(arr_random)}
Дисперсия: {np.var(arr_random)}""")

Случайный массив:
[[1 2 4]
 [2 3 1]]
Среднее: 2.1666666666666665
Медиана: 2.0
Стандартное отклонение: 1.0671873729054748
Дисперсия: 1.1388888888888888
